### ISSUE TITLE
Trying to do NFT Wallet Swap. Getting "Acknowledge activation to proceed."

### ISSUE THREAD

**Issue by Sofreshizzy** [cobmin/Maize#4]
Trying to do NFT Wallet Swap. Getting "Acknowledge activation to proceed."

Any help here?

![maize_issue](https://github.com/cobmin/Maize/assets/62079506/9597b3ad-4c29-41ac-9e9c-029a400e128e)

**Comment by jacobhuberonline** [comment]
Hey this has since been resolved. Download the new package under v1.1.8. Thanks for reaching out.
