### ISSUE TITLE
Encrypt all sensitive keys

### ISSUE THREAD

**Issue by fudgebucket27** [cobmin/Maize#5]
Probably should have a way to encrypt the private keys and api keys on the PC running Maize and then decrypt them using the passcode/passphrase that encrypted them when you enter the app. Just so they aren't sitting in plain text on the computer. LooPyGen has an option like this I believe.

**Comment by jacobhuberonline** [comment]
This is a great idea since the user no longer needs to touch the file itself.

**Comment by jacobhuberonline** [comment]
next release (v1.11.0) will have account management in it. user will have to enter in a password to log in. there will also be two keys that are stored in the application that will be hard to get to (why the user password is necessary). the source code for the encryption keys and process will not be open source. 

thanks for the push @fudgebucket27 ^_^

**Comment by fudgebucket27** [comment]
Awesome mate! Feel free to close this out as you've implemented it now 😊
